### ISSUE TITLE
Failed to import - gh/bablr-lang/bablr-vm

### ISSUE THREAD

**Issue by conartist6** [esm-dev/esm.sh#761]
## Failing module

- **GitHub**: https://github.com/bablr-lang/bablr-vm

```js
import { parseCSTML } from 'https://esm.sh/gh/bablr-lang/bablr-vm@709bd7899c585c18194baf9b730e38702272fa90';
```

## Error message

After running `deno run` I got this:

```
error: Import 'https://esm.sh/v134/@bablr/boot-helpers@0.0.0/denonext/template.js' failed: 500 Internal Server Error
    at https://esm.sh/gh/bablr-lang/bablr-vm@709bd7899c585c18194baf9b730e38702272fa90:4:8
```

The error indicates that the wrong URL is being imported. The correct URL to import would be:

```
https://esm.sh/v134/gh/bablr-lang/boot-helpers@1551598bc7257481089d06839eeec2e26885bbb2/es2022/lib/template.js
```

This is because my `package.json` contains:

```json
  "dependencies": {
    "@bablr/boot-helpers": "github:bablr-lang/boot-helpers#1551598bc7257481089d06839eeec2e26885bbb2",
  },
```

## Additional info

- **esm.sh version**: 134

**Comment by ije** [comment]
thanks for the details, i will look into

**Comment by conartist6** [comment]
I have a suspicion that pnpm is involved, as `pnpm` is the only thing that knows that the version the resolved github package claims to be is `0.0.0`.

From `pnpm-lock.yaml`:
```yaml
  github.com/bablr-lang/boot-helpers/1551598bc7257481089d06839eeec2e26885bbb2:
    resolution: {tarball: https://codeload.github.com/bablr-lang/boot-helpers/tar.gz/1551598bc7257481089d06839eeec2e26885bbb2}
    name: '@bablr/boot-helpers'
    version: 0.0.0
    engines: {node: '>=12.0.0'}
```
